clear; close all;
plotStyle()

% What things mean:
% x -> the input signal that was sent to the shaker (we recorded it)
% v -> the signal generated by the cymbal
% y -> the signal generated by the loudspeaker


%----- Setup

% Setting the channels
ch_shaker = 0;
ch_microphone = 1;

% Setting the IDs
cymbalID = 1;
loudspeakerID = 3;
combinedID = 4;

% Other information
fs = 102400;
pref = 20e-6;
xlimits = [200,20e3];

%----- Loading the information

% Cymbal
[only_cymbal_shaker, ~] = getTimeSeries('Data',cymbalID,ch_shaker,fs,'PlotResult',false);
[only_cymbal_microphone, ~] = getTimeSeries('Data',cymbalID,ch_microphone,fs,'PlotResult',false);

% Loudspeaker
[only_loudspeaker_shaker, ~] = getTimeSeries('Data',loudspeakerID,ch_shaker,fs,'PlotResult',false);
[only_loudspeaker_microphone, ~] = getTimeSeries('Data',loudspeakerID,ch_microphone,fs,'PlotResult',false);

% Cymbal + Loudspeaker
[combined_shaker, ~] = getTimeSeries('Data',combinedID,ch_shaker,fs,'PlotResult',false);
[combined_microphone, ~] = getTimeSeries('Data',combinedID,ch_microphone,fs,'PlotResult',false);

%----- Calculating the measured values
ns = fs/10;

% Just the input
[Gxx_measured, f, ~] = autospec(only_cymbal_shaker,fs,ns);

% Just the cymbal
[Gvv_measured, ~, ~] = autospec(only_cymbal_microphone,fs,ns);

% Just the loudspeaker
[Gnn_measured, ~, ~] = autospec(only_loudspeaker_microphone,fs,ns);

%----- Plotting the measured values together

figure()
semilogx(f,10.*log10(Gxx_measured./pref^2),'LineWidth',2)
hold on
semilogx(f,10.*log10(Gvv_measured./pref^2),'LineWidth',2)
semilogx(f,10.*log10(Gnn_measured./pref^2),'LineWidth',2)
title('The Different Components (Measured Separately)')
xlim(xlimits)
xlabel('Frequency (Hz)')
ylabel('Autospectral Density (dB)')
legend('Input Spectrum (G_{xx})', 'Cymbal Spectrum (G_{vv})', 'Noise Spectrum (G_{nn}, Loudspeaker)','Location','SouthWest')
%legend('Input Spectrum (G_{xx}, The Input)','Coherent Output Spectrum (G_{vv}, The Cymbal))',...
%    'Noise Output Spectrum (G_{nn}, The Loudspeaker)','Location','SouthWest')
grid on

%----- Calculating the transfer function Hxv and coherence
ns_Hxv = fs/5;
[Gxx_measured_for_Hxv, f_Hxv, ~] = autospec(only_cymbal_shaker,fs,ns_Hxv);
[Gvv_measured_for_Hxv, ~, ~] = autospec(only_cymbal_microphone,fs,ns_Hxv);
[Gxv_measured_for_Hxv, ~] = crossspec(only_cymbal_shaker,only_cymbal_microphone,fs,ns_Hxv);

Hxv = Gxv_measured_for_Hxv ./ Gxx_measured_for_Hxv;

gamma_squared_xv = abs(Gxv_measured_for_Hxv).^2 ./ (Gxx_measured_for_Hxv .* Gvv_measured_for_Hxv);

figure()
semilogx(f_Hxv,10*log10(abs(Hxv)/1),'Linewidth',2)
title('Transfer Function (H_{xv})')
xlabel('Frequency (Hz)')
ylabel('Gain (dB)')
xlim(xlimits)
grid on

figure()
semilogx(f_Hxv,angle(Hxv) .* 180/pi,'Linewidth',2)
title('Transfer Function (H_{xv})')
xlabel('Frequency (Hz)')
ylabel('Phase')
xlim(xlimits)
grid on

figure()
semilogx(f_Hxv,gamma_squared_xv,'Linewidth',2)
title('Shaker and Cymbal Coherence (\gamma^2_{xv})')
xlabel('Frequency (Hz)')
ylabel('Coherence')
xlim(xlimits)
grid on

%----- Calculating the values when both are combined

% Just the input
[Gxx_measured_combined, f, ~] = autospec(only_cymbal_shaker,fs,ns);

% Microphone-recorded autospectrum
[Gyy, ~, ~] = autospec(combined_microphone,fs,ns);

% Input and Microphone crossspectrum
[Gxy, ~] = crossspec(combined_shaker,combined_microphone,fs,ns);

%----- Calculating the coherence
gamma_squared_xy = abs(Gxy).^2 ./ (Gxx_measured_combined .* Gyy);

%----- Calculating Gvv and Gnn
Gvv_extracted = gamma_squared_xy .* Gyy; % The Coherent Output Spectrum
Gnn_extracted = (1 - gamma_squared_xy) .* Gyy; % The Incoherent Output Spectrum

%----- Comparing the measured and decomposed values
figure()
semilogx(f,10.*log10(Gnn_measured./pref^2),'Linewidth',2)
hold on
semilogx(f,10.*log10(Gnn_extracted./pref^2),'Linewidth',2)
semilogx(f,10.*log10(Gvv_measured./pref^2),'Linewidth',2)
semilogx(f,10.*log10(Gvv_extracted./pref^2),'Linewidth',2)
title('Extracting the Cymbal Sound')
xlabel('Frequency (Hz)')
ylabel('Autospectral Density (dB)')
xlim(xlimits)
legend('Loudspeaker (Measured)','Loudspeaker (Extracted)','Cymbal (Measured)','Cymbal (Extracted)','Location','SouthWest')
grid on

figure()
semilogx(f,gamma_squared_xy,'Linewidth',2)
title('Shaker and Recorded Signal Coherence (\gamma^2_{xy})')
xlabel('Frequency (Hz)')
ylabel('Coherence')
xlim(xlimits)
grid on

